#!/bin/bash

INFILE="$DATADIR/square.obj"
OUTFILE="$TEMPDIR/translatez.obj"
REFFILE="$DATADIR/square-translatez_-1.obj"

$BIN --translatez -1 "$INFILE" > "$OUTFILE"

cmp -s "$REFFILE" "$OUTFILE"
exit $?

