#!/bin/bash

INFILE="$DATADIR/square.obj"
OUTFILE="$TEMPDIR/translatex.obj"
REFFILE="$DATADIR/square-translatex_-5.obj"

$BIN --translatex -5 "$INFILE" > "$OUTFILE"

cmp -s "$REFFILE" "$OUTFILE"
exit $?

