#!/bin/bash

INFILE="$DATADIR/square.obj"
OUTFILE="$TEMPDIR/translate.obj"
REFFILE="$DATADIR/square-translate_10.obj"

$BIN --translate 10 "$INFILE" > "$OUTFILE"

cmp -s "$REFFILE" "$OUTFILE"
exit $?

